# Generated by Django 3.1 on 2020-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200807_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
